# Configuration file for the Sphinx documentation builder.

# -- Project information

project = 'ArxivDailyPaper'
copyright = '2024, JiamuZhou'
author = 'JiamuZhou'

release = ''
version = ''

# -- General configuration

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.doctest',
    'sphinx.ext.mathjax',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
    "myst_parser"
]

myst_heading_anchors = 4

autosummary_generate = True
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
# language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'furo' # 'sphinx_rtd_theme'

html_theme_options = {
    # "sidebar_hide_name": True,
    "light_css_variables": {
        "font-stack": "Helvetica, Arial, sans-serif, -apple-system",
        "font-stack--monospace": "Courier, monospace",
        "color-brand-primary": "#E5261F",
        "color-brand-content": "#E5261F",
        "admonition-font-size": "1rem",
        "admonition-title-font-size": "1rem",
        "font-size--small--2": "var(--font-size--small)",
    },
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['static']

add_module_names = False